version: 0.0
os: linux

files:
  - source: /server/juse
    destination: /home/ec2-user/codedeploy
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ec2-user/codedeploy
    pattern:  "**"
    mode: 755
    type:
      - file

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      owner: ubuntu
      group: ubuntu
      runas: root