version: 0.0
os: linux

files:
  - source: /server/juse
    destination: /home/ec2-user/codedeploy/build
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user/codedeploy/build
    pattern:  "**"
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: server_clear.sh
      timeout: 3000
      runas: root
  AfterInstall:
    - location: initialize.sh
      timeout: 3000
      runas: root
  ApplicationStart:
    - location: server_start.sh
      timeout: 3000
      runas: root
  ApplicationStop:
    - location: server_stop.sh
      timeout: 3000
      runas: root