# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "thom-droid-patch-1" ]
  pull_request:
    branches: [ "refactoring-2" ]

permissions:
  contents: read

#defaults:
#  run:
#    working-directory: d

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Moving to directory
      run: |
        pwd
        ls
        cd server/juse
        ls
    - name: Setup gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.5
    - name: Gradle init and permission
      run: |
        cd server/juse
        gradlew init
    - name: Build with Gradle
      run: server/juse/gradlew build


#
#    - uses: actions/upload-artifact@v3
#      if: failure()
#      with:
#        name: report
#        path: build/reports/

